In [1]:
import os
import sys
import numpy as np
import torch 
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
import nibabel as nib
from scipy import ndimage

In [2]:
print("CUDA available:", torch.cuda.is_available())
print("Number of GPUs:", torch.cuda.device_count())

CUDA available: True
Number of GPUs: 1


In [3]:

def read_nifti_file(filepath):
    """Read and load volume"""
    scan = nib.load(filepath)
    scan = scan.get_fdata()
    return scan

def normalize(volume):
    min = -1000
    max = 400
    volume[volume < min] = min
    volume[volume > max] = max
    volume = (volume - min) / (max - min)
    volume = volume.astype("float32")
    return volume

def resize_volume(img):
    desired_depth = 64
    desired_width = 128
    desired_height = 128
    current_depth = img.shape[-1]
    current_width = img.shape[0]
    current_height = img.shape[1]
    depth = current_depth / desired_depth
    width = current_width / desired_width
    height = current_height / desired_height
    depth_factor = 1 / depth
    width_factor = 1 / width
    height_factor = 1 / height
    img = ndimage.rotate(img, 90, reshape=False)
    img = ndimage.zoom(img, (width_factor, height_factor, depth_factor), order=1)
    return img

def process_scan(path):
    volume = read_nifti_file(path)
    volume = normalize(volume)
    volume = resize_volume(volume)
    return volume

In [4]:
normal_scan_paths = [
    os.path.join(os.getcwd(), "MosMedData/CT-0", x)
    for x in os.listdir("MosMedData/CT-0")if x[-1] == 'z'
]
abnormal_scan_paths = [
    os.path.join(os.getcwd(), "MosMedData/CT-23", x)
    for x in os.listdir("MosMedData/CT-23")if x[-1] == 'z'
]
print("CT scans with normal lung tissue: " + str(len(normal_scan_paths)))
print("CT scans with abnormal lung tissue: " + str(len(abnormal_scan_paths)))




CT scans with normal lung tissue: 254
CT scans with abnormal lung tissue: 856


In [5]:
# Read and process the scans.
# Each scan is resized across height, width, and depth and rescaled.
normal_scans = np.array([process_scan(path) for path in normal_scan_paths])
# assign 1, for the normal ones assign 0.
normal_labels = np.array([0 for _ in range(len(normal_scans))])
norm_split = round(len(normal_scans) * .9 )

In [6]:
abnormal_scans = np.array([process_scan(path) for path in abnormal_scan_paths])
abnormal_labels = np.array([1 for _ in range(len(abnormal_scans))])
abnorm_split = round(len(abnormal_scans) * .9 )

In [7]:
print("Normal scans in x train",normal_scans[:norm_split].shape)
print("Normal scans in X val ",normal_scans[norm_split:].shape)

print("Abormal scans in x train",abnormal_scans[:abnorm_split].shape)
print("Abormal scans in X val ",abnormal_scans[abnorm_split:].shape)


Normal scans in x train (229, 128, 128, 64)
Normal scans in X val  (25, 128, 128, 64)
Abormal scans in x train (770, 128, 128, 64)
Abormal scans in X val  (86, 128, 128, 64)


In [8]:
# Split data in the ratio 70-30 for training and validation.
x_train = np.concatenate((abnormal_scans[:abnorm_split], normal_scans[:norm_split]), axis=0)
y_train = np.concatenate((abnormal_labels[:abnorm_split], normal_labels[:norm_split]), axis=0)
x_val = np.concatenate((abnormal_scans[abnorm_split:], normal_scans[norm_split:]), axis=0)
y_val = np.concatenate((abnormal_labels[abnorm_split:], normal_labels[norm_split:]), axis=0)

In [9]:
print("x train shape", x_train.shape)
print("y train shape", y_train.shape)
print("x val shape", x_val.shape)
print("y val shape", y_val.shape)

x train shape (999, 128, 128, 64)
y train shape (999,)
x val shape (111, 128, 128, 64)
y val shape (111,)


In [10]:
print("Shape of abnormal scans:", abnormal_scans.shape)
print("Shape of normal scans:", normal_scans.shape)


Shape of abnormal scans: (856, 128, 128, 64)
Shape of normal scans: (254, 128, 128, 64)


In [11]:
class CTScansDataset(Dataset):
    def __init__(self, x, y, transform=None):
        self.x = x
        self.y = y
        self.transform = transform

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()

        image = self.x[idx]
        label = self.y[idx]

        if self.transform:
            image = self.transform(image)
        image = torch.from_numpy(image)
        image = image.unsqueeze(0)

        return (image, label)

# class RandomRotation3D:
#     def __init__(self, angles):
#         self.angles = angles

#     def __call__(self, image):
#         angle = np.random.choice(self.angles)
#         image = ndimage.rotate(image, angle, reshape=False)
#         image[image < 0] = 0
#         image[image > 1] = 1
#         return image


class NumpyToTensor:
    def __call__(self, image):
        return torch.from_numpy(image)

In [12]:
# train_transform = transforms.Compose([
# RandomRotation3D(angles=[-20, -10, -5, 5, 10, 20]),
# NumpyToTensor(),
# ])

# train_transform = transforms.Compose([
# NumpyToTensor(),
# ])
# val_transform = transforms.Compose([
# NumpyToTensor(),
# ])


train_transform = None
val_transform = None 

train_dataset = CTScansDataset(x_train, y_train, transform=train_transform)
val_dataset = CTScansDataset(x_val, y_val, transform=val_transform)

batch_size = 4
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
validation_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=True)

In [13]:
from resnet import ResNet, BasicBlock


class ModifiedResNet(ResNet):

    def __init__(self, *args, **kwargs):
        super(ModifiedResNet, self).__init__(*args, **kwargs)
        
        self.avgpool = nn.AdaptiveAvgPool3d(1)
        self.fc = nn.Linear(512 * kwargs["block"].expansion, 1)
        self.dropout = nn.Dropout(0.1)

    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)
        x = self.layer1(x)
        x = self.dropout(x) 
        x = self.layer2(x)
        x = self.dropout(x) 
        x = self.layer3(x)
        x = self.dropout(x) 
        x = self.layer4(x)
        
        x = self.avgpool(x)
        x = torch.flatten(x, 1)
        x = self.fc(x)
        x = self.dropout(x) 
        x = torch.sigmoid(x)
        
        return x


In [14]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
learning_rate = 0.0001
# Create the model instance

model = ModifiedResNet(block=BasicBlock, layers=[3, 4, 6, 3], sample_input_W=128, sample_input_H=128, sample_input_D=64, num_seg_classes=1).to(device)


# Load the pre-trained model's state_dict
pretrained_state_dict = torch.load("pretrain/resnet_34_23dataset.pth")


# Check if the state_dict is saved under the "state_dict" key and extract it
if "state_dict" in pretrained_state_dict:
    pretrained_state_dict = pretrained_state_dict["state_dict"]


# Remove 'module.' prefix from keys if it exists
corrected_state_dict = {k.replace("module.", ""): v for k, v in pretrained_state_dict.items()}


# Find the keys present in both the pre-trained model and your ModifiedResNet model
common_keys = set(corrected_state_dict.keys()) & set(model.state_dict().keys())


# Create a new state_dict with only the common keys
filtered_state_dict = {k: corrected_state_dict[k] for k in common_keys}


# Load the filtered state_dict into your model, allowing for partial weights with strict=False
model.load_state_dict(filtered_state_dict, strict=False)


# # Wrap the model with DataParallel
if torch.cuda.device_count() > 1:
    model = torch.nn.DataParallel(model)


criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
# scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.0001)
scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma = 0.96)



cuda


In [15]:
import matplotlib.pyplot as plt
import seaborn as sns

def plot_confusion_matrix(conf_matrix, class_names):
    fig, ax = plt.subplots(figsize=(6, 6))
    sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues", ax=ax, cbar=False)
    ax.set_xlabel("Predicted")
    ax.set_ylabel("True")
    ax.set_xticklabels(class_names)
    ax.set_yticklabels(class_names)
    plt.close(fig)
    return fig

In [17]:
from sklearn.metrics import confusion_matrix, f1_score, recall_score
import tqdm
import ipdb
from torch.utils.tensorboard import SummaryWriter

writer = SummaryWriter()

# ... (all previous code remains the same)
num_epochs = 100
best_val_acc = 0.0
best_epoch = 0

for epoch in range(num_epochs):
    for phase in ['train', 'val']:
        if phase == 'train':
            model.train()
            data_loader = train_loader
            dataset = train_dataset
        else:
            model.eval()
            data_loader = validation_loader
            dataset = val_dataset

        running_loss = 0.0
        running_corrects = 0
        all_preds = []
        all_labels = []

        for inputs, labels in tqdm.tqdm(data_loader, desc=f"{phase.capitalize()} Epoch {epoch}"):
            inputs, labels = inputs.to(device), labels.to(device)
            optimizer.zero_grad()

            with torch.set_grad_enabled(phase == 'train'):
                outputs = model(inputs)
                outputs = outputs.view(-1)
                loss = criterion(outputs, labels.float())
                
                preds = (outputs > 0.5).float()

                if phase == 'train':
                    loss.backward()
                    optimizer.step()

            running_loss += loss.item() * inputs.size(0)
            running_corrects += torch.sum(preds == labels.data)
            # ipdb.set_trace(context=5)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

        epoch_loss = running_loss / len(dataset)
        epoch_acc = running_corrects.double() / len(dataset)

        if phase == 'val':
            # Calculate confusion matrix, F1 score, and recall
            conf_matrix = confusion_matrix(all_labels, all_preds)
            f1 = f1_score(all_labels, all_preds, average='weighted')
            recall = recall_score(all_labels, all_preds, average='weighted')

            # Print confusion matrix, F1 score, and recall
            print(f"Confusion matrix for epoch {epoch}:\n{conf_matrix}")
            print(f'Epoch {epoch}/{num_epochs - 1}, {phase.capitalize()} F1 Score: {f1:.4f}, {phase.capitalize()} Recall: {recall:.4f}')

            # Log confusion matrix to TensorBoard
            writer.add_figure("Confusion Matrix/val", plot_confusion_matrix(conf_matrix, ["Normal", "Abnormal"]), epoch)

        if phase == 'train':
            scheduler.step()
            writer.add_scalar('Loss/train', epoch_loss, epoch)
            writer.add_scalar('Accuracy/train', epoch_acc, epoch)
        else:
            writer.add_scalar('Loss/val', epoch_loss, epoch)
            writer.add_scalar('Accuracy/val', epoch_acc, epoch)

        print(f'Epoch {epoch}/{num_epochs - 1}, {phase.capitalize()} Loss: {epoch_loss:.4f}, {phase.capitalize()} Accuracy: {epoch_acc:.4f}')

        if phase == 'val' and epoch_acc > best_val_acc:
            best_val_acc = epoch_acc
            best_epoch = epoch
            best_model_wts = model.state_dict()

torch.save(best_model_wts, '3d_image_classification.pth')
print(f"Training complete. Best validation accuracy: {best_val_acc:.4f} at epoch {best_epoch}")


Train Epoch 0: 100%|██████████| 250/250 [01:29<00:00,  2.80it/s]


Epoch 0/99, Train Loss: 0.5572, Train Accuracy: 0.7187


Val Epoch 0: 100%|██████████| 28/28 [00:04<00:00,  6.57it/s]


Confusion matrix for epoch 0:
[[ 0 25]
 [ 0 86]]
Epoch 0/99, Val F1 Score: 0.6765, Val Recall: 0.7748
Epoch 0/99, Val Loss: 0.5300, Val Accuracy: 0.7748


Train Epoch 1: 100%|██████████| 250/250 [01:36<00:00,  2.60it/s]


Epoch 1/99, Train Loss: 0.5384, Train Accuracy: 0.7197


Val Epoch 1: 100%|██████████| 28/28 [00:03<00:00,  7.59it/s]


Confusion matrix for epoch 1:
[[ 0 25]
 [ 0 86]]
Epoch 1/99, Val F1 Score: 0.6765, Val Recall: 0.7748
Epoch 1/99, Val Loss: 0.5146, Val Accuracy: 0.7748


Train Epoch 2: 100%|██████████| 250/250 [01:39<00:00,  2.52it/s]


Epoch 2/99, Train Loss: 0.5281, Train Accuracy: 0.7307


Val Epoch 2: 100%|██████████| 28/28 [00:04<00:00,  6.50it/s]


Confusion matrix for epoch 2:
[[ 0 25]
 [ 0 86]]
Epoch 2/99, Val F1 Score: 0.6765, Val Recall: 0.7748
Epoch 2/99, Val Loss: 0.4531, Val Accuracy: 0.7748


Train Epoch 3: 100%|██████████| 250/250 [01:40<00:00,  2.48it/s]


Epoch 3/99, Train Loss: 0.5305, Train Accuracy: 0.7157


Val Epoch 3: 100%|██████████| 28/28 [00:04<00:00,  6.71it/s]


Confusion matrix for epoch 3:
[[ 3 22]
 [ 0 86]]
Epoch 3/99, Val F1 Score: 0.7352, Val Recall: 0.8018
Epoch 3/99, Val Loss: 0.4553, Val Accuracy: 0.8018


Train Epoch 4: 100%|██████████| 250/250 [01:42<00:00,  2.44it/s]


Epoch 4/99, Train Loss: 0.5137, Train Accuracy: 0.7057


Val Epoch 4: 100%|██████████| 28/28 [00:04<00:00,  6.93it/s]


Confusion matrix for epoch 4:
[[16  9]
 [19 67]]
Epoch 4/99, Val F1 Score: 0.7610, Val Recall: 0.7477
Epoch 4/99, Val Loss: 0.5295, Val Accuracy: 0.7477


Train Epoch 5: 100%|██████████| 250/250 [01:43<00:00,  2.43it/s]


Epoch 5/99, Train Loss: 0.5174, Train Accuracy: 0.7157


Val Epoch 5: 100%|██████████| 28/28 [00:04<00:00,  6.94it/s]


Confusion matrix for epoch 5:
[[ 1 24]
 [ 0 86]]
Epoch 5/99, Val F1 Score: 0.6972, Val Recall: 0.7838
Epoch 5/99, Val Loss: 0.6426, Val Accuracy: 0.7838


Train Epoch 6: 100%|██████████| 250/250 [01:40<00:00,  2.48it/s]


Epoch 6/99, Train Loss: 0.5010, Train Accuracy: 0.7357


Val Epoch 6: 100%|██████████| 28/28 [00:03<00:00,  7.30it/s]


Confusion matrix for epoch 6:
[[ 1 24]
 [ 0 86]]
Epoch 6/99, Val F1 Score: 0.6972, Val Recall: 0.7838
Epoch 6/99, Val Loss: 0.5411, Val Accuracy: 0.7838


Train Epoch 7: 100%|██████████| 250/250 [01:40<00:00,  2.48it/s]


Epoch 7/99, Train Loss: 0.4883, Train Accuracy: 0.7417


Val Epoch 7: 100%|██████████| 28/28 [00:03<00:00,  7.40it/s]


Confusion matrix for epoch 7:
[[ 0 25]
 [ 0 86]]
Epoch 7/99, Val F1 Score: 0.6765, Val Recall: 0.7748
Epoch 7/99, Val Loss: 0.4974, Val Accuracy: 0.7748


Train Epoch 8: 100%|██████████| 250/250 [01:40<00:00,  2.49it/s]


Epoch 8/99, Train Loss: 0.4992, Train Accuracy: 0.7327


Val Epoch 8: 100%|██████████| 28/28 [00:03<00:00,  7.31it/s]


Confusion matrix for epoch 8:
[[ 1 24]
 [ 1 85]]
Epoch 8/99, Val F1 Score: 0.6921, Val Recall: 0.7748
Epoch 8/99, Val Loss: 0.5008, Val Accuracy: 0.7748


Train Epoch 9: 100%|██████████| 250/250 [01:39<00:00,  2.50it/s]


Epoch 9/99, Train Loss: 0.4727, Train Accuracy: 0.7357


Val Epoch 9: 100%|██████████| 28/28 [00:03<00:00,  7.37it/s]


Confusion matrix for epoch 9:
[[ 0 25]
 [ 0 86]]
Epoch 9/99, Val F1 Score: 0.6765, Val Recall: 0.7748
Epoch 9/99, Val Loss: 0.5046, Val Accuracy: 0.7748


Train Epoch 10: 100%|██████████| 250/250 [01:39<00:00,  2.50it/s]


Epoch 10/99, Train Loss: 0.4733, Train Accuracy: 0.7167


Val Epoch 10: 100%|██████████| 28/28 [00:03<00:00,  7.36it/s]


Confusion matrix for epoch 10:
[[ 6 19]
 [ 8 78]]
Epoch 10/99, Val F1 Score: 0.7298, Val Recall: 0.7568
Epoch 10/99, Val Loss: 0.5600, Val Accuracy: 0.7568


Train Epoch 11: 100%|██████████| 250/250 [01:39<00:00,  2.50it/s]


Epoch 11/99, Train Loss: 0.4879, Train Accuracy: 0.7257


Val Epoch 11: 100%|██████████| 28/28 [00:03<00:00,  7.40it/s]


Confusion matrix for epoch 11:
[[ 7 18]
 [ 2 84]]
Epoch 11/99, Val F1 Score: 0.7851, Val Recall: 0.8198
Epoch 11/99, Val Loss: 0.4463, Val Accuracy: 0.8198


Train Epoch 12: 100%|██████████| 250/250 [01:39<00:00,  2.50it/s]


Epoch 12/99, Train Loss: 0.4651, Train Accuracy: 0.7337


Val Epoch 12: 100%|██████████| 28/28 [00:03<00:00,  7.40it/s]


Confusion matrix for epoch 12:
[[ 7 18]
 [ 1 85]]
Epoch 12/99, Val F1 Score: 0.7924, Val Recall: 0.8288
Epoch 12/99, Val Loss: 0.4275, Val Accuracy: 0.8288


Train Epoch 13: 100%|██████████| 250/250 [01:39<00:00,  2.51it/s]


Epoch 13/99, Train Loss: 0.4652, Train Accuracy: 0.7347


Val Epoch 13: 100%|██████████| 28/28 [00:03<00:00,  7.36it/s]


Confusion matrix for epoch 13:
[[ 8 17]
 [ 2 84]]
Epoch 13/99, Val F1 Score: 0.7990, Val Recall: 0.8288
Epoch 13/99, Val Loss: 0.3912, Val Accuracy: 0.8288


Train Epoch 14: 100%|██████████| 250/250 [01:38<00:00,  2.53it/s]


Epoch 14/99, Train Loss: 0.4469, Train Accuracy: 0.7588


Val Epoch 14: 100%|██████████| 28/28 [00:04<00:00,  6.94it/s]


Confusion matrix for epoch 14:
[[ 5 20]
 [ 0 86]]
Epoch 14/99, Val F1 Score: 0.7691, Val Recall: 0.8198
Epoch 14/99, Val Loss: 0.4862, Val Accuracy: 0.8198


Train Epoch 15: 100%|██████████| 250/250 [01:39<00:00,  2.52it/s]


Epoch 15/99, Train Loss: 0.4663, Train Accuracy: 0.7317


Val Epoch 15: 100%|██████████| 28/28 [00:03<00:00,  7.58it/s]


Confusion matrix for epoch 15:
[[ 7 18]
 [ 2 84]]
Epoch 15/99, Val F1 Score: 0.7851, Val Recall: 0.8198
Epoch 15/99, Val Loss: 0.4406, Val Accuracy: 0.8198


Train Epoch 16: 100%|██████████| 250/250 [01:39<00:00,  2.52it/s]


Epoch 16/99, Train Loss: 0.4503, Train Accuracy: 0.7538


Val Epoch 16: 100%|██████████| 28/28 [00:03<00:00,  7.45it/s]


Confusion matrix for epoch 16:
[[ 6 19]
 [ 3 83]]
Epoch 16/99, Val F1 Score: 0.7636, Val Recall: 0.8018
Epoch 16/99, Val Loss: 0.4242, Val Accuracy: 0.8018


Train Epoch 17: 100%|██████████| 250/250 [01:39<00:00,  2.52it/s]


Epoch 17/99, Train Loss: 0.4528, Train Accuracy: 0.7508


Val Epoch 17: 100%|██████████| 28/28 [00:03<00:00,  7.37it/s]


Confusion matrix for epoch 17:
[[ 6 19]
 [ 1 85]]
Epoch 17/99, Val F1 Score: 0.7777, Val Recall: 0.8198
Epoch 17/99, Val Loss: 0.4312, Val Accuracy: 0.8198


Train Epoch 18: 100%|██████████| 250/250 [01:38<00:00,  2.53it/s]


Epoch 18/99, Train Loss: 0.4648, Train Accuracy: 0.7387


Val Epoch 18: 100%|██████████| 28/28 [00:03<00:00,  7.29it/s]


Confusion matrix for epoch 18:
[[ 9 16]
 [ 4 82]]
Epoch 18/99, Val F1 Score: 0.7972, Val Recall: 0.8198
Epoch 18/99, Val Loss: 0.4003, Val Accuracy: 0.8198


Train Epoch 19: 100%|██████████| 250/250 [01:38<00:00,  2.53it/s]


Epoch 19/99, Train Loss: 0.4401, Train Accuracy: 0.7518


Val Epoch 19: 100%|██████████| 28/28 [00:03<00:00,  7.34it/s]


Confusion matrix for epoch 19:
[[ 6 19]
 [ 1 85]]
Epoch 19/99, Val F1 Score: 0.7777, Val Recall: 0.8198
Epoch 19/99, Val Loss: 0.4478, Val Accuracy: 0.8198


Train Epoch 20: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 20/99, Train Loss: 0.4140, Train Accuracy: 0.7678


Val Epoch 20: 100%|██████████| 28/28 [00:03<00:00,  7.39it/s]


Confusion matrix for epoch 20:
[[ 5 20]
 [ 1 85]]
Epoch 20/99, Val F1 Score: 0.7622, Val Recall: 0.8108
Epoch 20/99, Val Loss: 0.5895, Val Accuracy: 0.8108


Train Epoch 21: 100%|██████████| 250/250 [01:39<00:00,  2.52it/s]


Epoch 21/99, Train Loss: 0.4397, Train Accuracy: 0.7598


Val Epoch 21: 100%|██████████| 28/28 [00:03<00:00,  7.40it/s]


Confusion matrix for epoch 21:
[[ 6 19]
 [ 2 84]]
Epoch 21/99, Val F1 Score: 0.7706, Val Recall: 0.8108
Epoch 21/99, Val Loss: 0.4097, Val Accuracy: 0.8108


Train Epoch 22: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 22/99, Train Loss: 0.4131, Train Accuracy: 0.7618


Val Epoch 22: 100%|██████████| 28/28 [00:03<00:00,  7.32it/s]


Confusion matrix for epoch 22:
[[ 8 17]
 [ 1 85]]
Epoch 22/99, Val F1 Score: 0.8066, Val Recall: 0.8378
Epoch 22/99, Val Loss: 0.4002, Val Accuracy: 0.8378


Train Epoch 23: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 23/99, Train Loss: 0.4332, Train Accuracy: 0.7718


Val Epoch 23: 100%|██████████| 28/28 [00:03<00:00,  7.23it/s]


Confusion matrix for epoch 23:
[[ 7 18]
 [ 1 85]]
Epoch 23/99, Val F1 Score: 0.7924, Val Recall: 0.8288
Epoch 23/99, Val Loss: 0.4114, Val Accuracy: 0.8288


Train Epoch 24: 100%|██████████| 250/250 [01:38<00:00,  2.53it/s]


Epoch 24/99, Train Loss: 0.4334, Train Accuracy: 0.7518


Val Epoch 24: 100%|██████████| 28/28 [00:03<00:00,  7.42it/s]


Confusion matrix for epoch 24:
[[ 5 20]
 [ 0 86]]
Epoch 24/99, Val F1 Score: 0.7691, Val Recall: 0.8198
Epoch 24/99, Val Loss: 0.4884, Val Accuracy: 0.8198


Train Epoch 25: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 25/99, Train Loss: 0.4103, Train Accuracy: 0.7678


Val Epoch 25: 100%|██████████| 28/28 [00:03<00:00,  7.47it/s]


Confusion matrix for epoch 25:
[[ 6 19]
 [ 1 85]]
Epoch 25/99, Val F1 Score: 0.7777, Val Recall: 0.8198
Epoch 25/99, Val Loss: 0.4336, Val Accuracy: 0.8198


Train Epoch 26: 100%|██████████| 250/250 [01:38<00:00,  2.53it/s]


Epoch 26/99, Train Loss: 0.4189, Train Accuracy: 0.7628


Val Epoch 26: 100%|██████████| 28/28 [00:03<00:00,  7.44it/s]


Confusion matrix for epoch 26:
[[ 7 18]
 [ 2 84]]
Epoch 26/99, Val F1 Score: 0.7851, Val Recall: 0.8198
Epoch 26/99, Val Loss: 0.4328, Val Accuracy: 0.8198


Train Epoch 27: 100%|██████████| 250/250 [01:38<00:00,  2.55it/s]


Epoch 27/99, Train Loss: 0.3959, Train Accuracy: 0.7788


Val Epoch 27: 100%|██████████| 28/28 [00:03<00:00,  7.47it/s]


Confusion matrix for epoch 27:
[[ 6 19]
 [ 2 84]]
Epoch 27/99, Val F1 Score: 0.7706, Val Recall: 0.8108
Epoch 27/99, Val Loss: 0.4420, Val Accuracy: 0.8108


Train Epoch 28: 100%|██████████| 250/250 [01:37<00:00,  2.55it/s]


Epoch 28/99, Train Loss: 0.3993, Train Accuracy: 0.7628


Val Epoch 28: 100%|██████████| 28/28 [00:03<00:00,  7.48it/s]


Confusion matrix for epoch 28:
[[ 7 18]
 [ 4 82]]
Epoch 28/99, Val F1 Score: 0.7707, Val Recall: 0.8018
Epoch 28/99, Val Loss: 0.4225, Val Accuracy: 0.8018


Train Epoch 29: 100%|██████████| 250/250 [01:38<00:00,  2.53it/s]


Epoch 29/99, Train Loss: 0.4194, Train Accuracy: 0.7708


Val Epoch 29: 100%|██████████| 28/28 [00:03<00:00,  7.31it/s]


Confusion matrix for epoch 29:
[[ 8 17]
 [ 1 85]]
Epoch 29/99, Val F1 Score: 0.8066, Val Recall: 0.8378
Epoch 29/99, Val Loss: 0.3784, Val Accuracy: 0.8378


Train Epoch 30: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 30/99, Train Loss: 0.4095, Train Accuracy: 0.7638


Val Epoch 30: 100%|██████████| 28/28 [00:03<00:00,  7.57it/s]


Confusion matrix for epoch 30:
[[ 7 18]
 [ 2 84]]
Epoch 30/99, Val F1 Score: 0.7851, Val Recall: 0.8198
Epoch 30/99, Val Loss: 0.4292, Val Accuracy: 0.8198


Train Epoch 31: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 31/99, Train Loss: 0.3740, Train Accuracy: 0.7858


Val Epoch 31: 100%|██████████| 28/28 [00:03<00:00,  7.52it/s]


Confusion matrix for epoch 31:
[[ 6 19]
 [ 2 84]]
Epoch 31/99, Val F1 Score: 0.7706, Val Recall: 0.8108
Epoch 31/99, Val Loss: 0.4743, Val Accuracy: 0.8108


Train Epoch 32: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 32/99, Train Loss: 0.3880, Train Accuracy: 0.7708


Val Epoch 32: 100%|██████████| 28/28 [00:03<00:00,  7.35it/s]


Confusion matrix for epoch 32:
[[ 6 19]
 [ 1 85]]
Epoch 32/99, Val F1 Score: 0.7777, Val Recall: 0.8198
Epoch 32/99, Val Loss: 0.5158, Val Accuracy: 0.8198


Train Epoch 33: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 33/99, Train Loss: 0.3576, Train Accuracy: 0.8058


Val Epoch 33: 100%|██████████| 28/28 [00:03<00:00,  7.43it/s]


Confusion matrix for epoch 33:
[[ 7 18]
 [ 2 84]]
Epoch 33/99, Val F1 Score: 0.7851, Val Recall: 0.8198
Epoch 33/99, Val Loss: 0.3931, Val Accuracy: 0.8198


Train Epoch 34: 100%|██████████| 250/250 [01:38<00:00,  2.55it/s]


Epoch 34/99, Train Loss: 0.3722, Train Accuracy: 0.7848


Val Epoch 34: 100%|██████████| 28/28 [00:03<00:00,  7.49it/s]


Confusion matrix for epoch 34:
[[ 7 18]
 [ 2 84]]
Epoch 34/99, Val F1 Score: 0.7851, Val Recall: 0.8198
Epoch 34/99, Val Loss: 0.4573, Val Accuracy: 0.8198


Train Epoch 35: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 35/99, Train Loss: 0.3655, Train Accuracy: 0.7948


Val Epoch 35: 100%|██████████| 28/28 [00:03<00:00,  7.48it/s]


Confusion matrix for epoch 35:
[[11 14]
 [ 5 81]]
Epoch 35/99, Val F1 Score: 0.8143, Val Recall: 0.8288
Epoch 35/99, Val Loss: 0.3714, Val Accuracy: 0.8288


Train Epoch 36: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 36/99, Train Loss: 0.3596, Train Accuracy: 0.7868


Val Epoch 36: 100%|██████████| 28/28 [00:03<00:00,  7.48it/s]


Confusion matrix for epoch 36:
[[ 8 17]
 [ 5 81]]
Epoch 36/99, Val F1 Score: 0.7770, Val Recall: 0.8018
Epoch 36/99, Val Loss: 0.4491, Val Accuracy: 0.8018


Train Epoch 37: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 37/99, Train Loss: 0.3492, Train Accuracy: 0.7818


Val Epoch 37: 100%|██████████| 28/28 [00:03<00:00,  7.73it/s]


Confusion matrix for epoch 37:
[[12 13]
 [ 5 81]]
Epoch 37/99, Val F1 Score: 0.8260, Val Recall: 0.8378
Epoch 37/99, Val Loss: 0.3765, Val Accuracy: 0.8378


Train Epoch 38: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 38/99, Train Loss: 0.3321, Train Accuracy: 0.8058


Val Epoch 38: 100%|██████████| 28/28 [00:03<00:00,  7.53it/s]


Confusion matrix for epoch 38:
[[ 9 16]
 [ 2 84]]
Epoch 38/99, Val F1 Score: 0.8124, Val Recall: 0.8378
Epoch 38/99, Val Loss: 0.4299, Val Accuracy: 0.8378


Train Epoch 39: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 39/99, Train Loss: 0.3466, Train Accuracy: 0.7938


Val Epoch 39: 100%|██████████| 28/28 [00:03<00:00,  7.48it/s]


Confusion matrix for epoch 39:
[[13 12]
 [ 8 78]]
Epoch 39/99, Val F1 Score: 0.8140, Val Recall: 0.8198
Epoch 39/99, Val Loss: 0.3817, Val Accuracy: 0.8198


Train Epoch 40: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 40/99, Train Loss: 0.3212, Train Accuracy: 0.8118


Val Epoch 40: 100%|██████████| 28/28 [00:03<00:00,  7.54it/s]


Confusion matrix for epoch 40:
[[ 7 18]
 [ 2 84]]
Epoch 40/99, Val F1 Score: 0.7851, Val Recall: 0.8198
Epoch 40/99, Val Loss: 0.5609, Val Accuracy: 0.8198


Train Epoch 41: 100%|██████████| 250/250 [01:38<00:00,  2.55it/s]


Epoch 41/99, Train Loss: 0.3322, Train Accuracy: 0.8138


Val Epoch 41: 100%|██████████| 28/28 [00:03<00:00,  7.56it/s]


Confusion matrix for epoch 41:
[[ 9 16]
 [ 5 81]]
Epoch 41/99, Val F1 Score: 0.7898, Val Recall: 0.8108
Epoch 41/99, Val Loss: 0.4085, Val Accuracy: 0.8108


Train Epoch 42: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 42/99, Train Loss: 0.3069, Train Accuracy: 0.8308


Val Epoch 42: 100%|██████████| 28/28 [00:03<00:00,  7.50it/s]


Confusion matrix for epoch 42:
[[ 5 20]
 [ 1 85]]
Epoch 42/99, Val F1 Score: 0.7622, Val Recall: 0.8108
Epoch 42/99, Val Loss: 0.5560, Val Accuracy: 0.8108


Train Epoch 43: 100%|██████████| 250/250 [01:38<00:00,  2.55it/s]


Epoch 43/99, Train Loss: 0.3089, Train Accuracy: 0.8248


Val Epoch 43: 100%|██████████| 28/28 [00:03<00:00,  7.45it/s]


Confusion matrix for epoch 43:
[[12 13]
 [ 6 80]]
Epoch 43/99, Val F1 Score: 0.8182, Val Recall: 0.8288
Epoch 43/99, Val Loss: 0.4282, Val Accuracy: 0.8288


Train Epoch 44: 100%|██████████| 250/250 [01:38<00:00,  2.55it/s]


Epoch 44/99, Train Loss: 0.3074, Train Accuracy: 0.8308


Val Epoch 44: 100%|██████████| 28/28 [00:03<00:00,  7.54it/s]


Confusion matrix for epoch 44:
[[ 9 16]
 [ 3 83]]
Epoch 44/99, Val F1 Score: 0.8048, Val Recall: 0.8288
Epoch 44/99, Val Loss: 0.4675, Val Accuracy: 0.8288


Train Epoch 45: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 45/99, Train Loss: 0.2878, Train Accuracy: 0.8408


Val Epoch 45: 100%|██████████| 28/28 [00:03<00:00,  7.58it/s]


Confusion matrix for epoch 45:
[[ 8 17]
 [ 3 83]]
Epoch 45/99, Val F1 Score: 0.7916, Val Recall: 0.8198
Epoch 45/99, Val Loss: 0.4980, Val Accuracy: 0.8198


Train Epoch 46: 100%|██████████| 250/250 [01:38<00:00,  2.55it/s]


Epoch 46/99, Train Loss: 0.2880, Train Accuracy: 0.8318


Val Epoch 46: 100%|██████████| 28/28 [00:03<00:00,  7.51it/s]


Confusion matrix for epoch 46:
[[ 8 17]
 [ 3 83]]
Epoch 46/99, Val F1 Score: 0.7916, Val Recall: 0.8198
Epoch 46/99, Val Loss: 0.5443, Val Accuracy: 0.8198


Train Epoch 47: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 47/99, Train Loss: 0.2827, Train Accuracy: 0.8358


Val Epoch 47: 100%|██████████| 28/28 [00:03<00:00,  7.61it/s]


Confusion matrix for epoch 47:
[[ 6 19]
 [ 2 84]]
Epoch 47/99, Val F1 Score: 0.7706, Val Recall: 0.8108
Epoch 47/99, Val Loss: 0.5321, Val Accuracy: 0.8108


Train Epoch 48: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 48/99, Train Loss: 0.2759, Train Accuracy: 0.8458


Val Epoch 48: 100%|██████████| 28/28 [00:03<00:00,  7.51it/s]


Confusion matrix for epoch 48:
[[ 5 20]
 [ 5 81]]
Epoch 48/99, Val F1 Score: 0.7355, Val Recall: 0.7748
Epoch 48/99, Val Loss: 0.5589, Val Accuracy: 0.7748


Train Epoch 49: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 49/99, Train Loss: 0.2518, Train Accuracy: 0.8509


Val Epoch 49: 100%|██████████| 28/28 [00:03<00:00,  7.46it/s]


Confusion matrix for epoch 49:
[[ 8 17]
 [ 3 83]]
Epoch 49/99, Val F1 Score: 0.7916, Val Recall: 0.8198
Epoch 49/99, Val Loss: 0.6326, Val Accuracy: 0.8198


Train Epoch 50: 100%|██████████| 250/250 [01:38<00:00,  2.55it/s]


Epoch 50/99, Train Loss: 0.2456, Train Accuracy: 0.8438


Val Epoch 50: 100%|██████████| 28/28 [00:03<00:00,  7.50it/s]


Confusion matrix for epoch 50:
[[ 6 19]
 [ 4 82]]
Epoch 50/99, Val F1 Score: 0.7567, Val Recall: 0.7928
Epoch 50/99, Val Loss: 0.6738, Val Accuracy: 0.7928


Train Epoch 51: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 51/99, Train Loss: 0.2311, Train Accuracy: 0.8759


Val Epoch 51: 100%|██████████| 28/28 [00:03<00:00,  7.54it/s]


Confusion matrix for epoch 51:
[[ 6 19]
 [ 3 83]]
Epoch 51/99, Val F1 Score: 0.7636, Val Recall: 0.8018
Epoch 51/99, Val Loss: 0.5878, Val Accuracy: 0.8018


Train Epoch 52: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 52/99, Train Loss: 0.2357, Train Accuracy: 0.8619


Val Epoch 52: 100%|██████████| 28/28 [00:03<00:00,  7.57it/s]


Confusion matrix for epoch 52:
[[ 6 19]
 [ 3 83]]
Epoch 52/99, Val F1 Score: 0.7636, Val Recall: 0.8018
Epoch 52/99, Val Loss: 0.5875, Val Accuracy: 0.8018


Train Epoch 53: 100%|██████████| 250/250 [01:38<00:00,  2.53it/s]


Epoch 53/99, Train Loss: 0.2646, Train Accuracy: 0.8318


Val Epoch 53: 100%|██████████| 28/28 [00:03<00:00,  7.48it/s]


Confusion matrix for epoch 53:
[[ 7 18]
 [ 3 83]]
Epoch 53/99, Val F1 Score: 0.7779, Val Recall: 0.8108
Epoch 53/99, Val Loss: 0.5497, Val Accuracy: 0.8108


Train Epoch 54: 100%|██████████| 250/250 [01:38<00:00,  2.55it/s]


Epoch 54/99, Train Loss: 0.2482, Train Accuracy: 0.8589


Val Epoch 54: 100%|██████████| 28/28 [00:03<00:00,  7.47it/s]


Confusion matrix for epoch 54:
[[ 7 18]
 [ 3 83]]
Epoch 54/99, Val F1 Score: 0.7779, Val Recall: 0.8108
Epoch 54/99, Val Loss: 0.5835, Val Accuracy: 0.8108


Train Epoch 55: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 55/99, Train Loss: 0.2177, Train Accuracy: 0.8749


Val Epoch 55: 100%|██████████| 28/28 [00:03<00:00,  7.46it/s]


Confusion matrix for epoch 55:
[[ 7 18]
 [ 3 83]]
Epoch 55/99, Val F1 Score: 0.7779, Val Recall: 0.8108
Epoch 55/99, Val Loss: 0.5882, Val Accuracy: 0.8108


Train Epoch 56: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 56/99, Train Loss: 0.2146, Train Accuracy: 0.8569


Val Epoch 56: 100%|██████████| 28/28 [00:03<00:00,  7.47it/s]


Confusion matrix for epoch 56:
[[ 3 22]
 [ 2 84]]
Epoch 56/99, Val F1 Score: 0.7230, Val Recall: 0.7838
Epoch 56/99, Val Loss: 0.6233, Val Accuracy: 0.7838


Train Epoch 57: 100%|██████████| 250/250 [01:38<00:00,  2.53it/s]


Epoch 57/99, Train Loss: 0.2102, Train Accuracy: 0.8689


Val Epoch 57: 100%|██████████| 28/28 [00:03<00:00,  7.68it/s]


Confusion matrix for epoch 57:
[[ 8 17]
 [ 5 81]]
Epoch 57/99, Val F1 Score: 0.7770, Val Recall: 0.8018
Epoch 57/99, Val Loss: 0.5568, Val Accuracy: 0.8018


Train Epoch 58: 100%|██████████| 250/250 [01:37<00:00,  2.55it/s]


Epoch 58/99, Train Loss: 0.2225, Train Accuracy: 0.8619


Val Epoch 58: 100%|██████████| 28/28 [00:03<00:00,  7.51it/s]


Confusion matrix for epoch 58:
[[ 8 17]
 [ 6 80]]
Epoch 58/99, Val F1 Score: 0.7698, Val Recall: 0.7928
Epoch 58/99, Val Loss: 0.5040, Val Accuracy: 0.7928


Train Epoch 59: 100%|██████████| 250/250 [01:38<00:00,  2.53it/s]


Epoch 59/99, Train Loss: 0.2009, Train Accuracy: 0.8719


Val Epoch 59: 100%|██████████| 28/28 [00:03<00:00,  7.45it/s]


Confusion matrix for epoch 59:
[[ 7 18]
 [ 5 81]]
Epoch 59/99, Val F1 Score: 0.7637, Val Recall: 0.7928
Epoch 59/99, Val Loss: 0.7200, Val Accuracy: 0.7928


Train Epoch 60: 100%|██████████| 250/250 [01:37<00:00,  2.55it/s]


Epoch 60/99, Train Loss: 0.2278, Train Accuracy: 0.8589


Val Epoch 60: 100%|██████████| 28/28 [00:03<00:00,  7.50it/s]


Confusion matrix for epoch 60:
[[ 7 18]
 [ 4 82]]
Epoch 60/99, Val F1 Score: 0.7707, Val Recall: 0.8018
Epoch 60/99, Val Loss: 0.6386, Val Accuracy: 0.8018


Train Epoch 61: 100%|██████████| 250/250 [01:37<00:00,  2.55it/s]


Epoch 61/99, Train Loss: 0.1892, Train Accuracy: 0.8659


Val Epoch 61: 100%|██████████| 28/28 [00:03<00:00,  7.43it/s]


Confusion matrix for epoch 61:
[[ 9 16]
 [ 5 81]]
Epoch 61/99, Val F1 Score: 0.7898, Val Recall: 0.8108
Epoch 61/99, Val Loss: 0.6137, Val Accuracy: 0.8108


Train Epoch 62: 100%|██████████| 250/250 [01:38<00:00,  2.55it/s]


Epoch 62/99, Train Loss: 0.1778, Train Accuracy: 0.8759


Val Epoch 62: 100%|██████████| 28/28 [00:03<00:00,  7.51it/s]


Confusion matrix for epoch 62:
[[10 15]
 [ 5 81]]
Epoch 62/99, Val F1 Score: 0.8022, Val Recall: 0.8198
Epoch 62/99, Val Loss: 0.5908, Val Accuracy: 0.8198


Train Epoch 63: 100%|██████████| 250/250 [01:37<00:00,  2.55it/s]


Epoch 63/99, Train Loss: 0.1732, Train Accuracy: 0.8929


Val Epoch 63: 100%|██████████| 28/28 [00:03<00:00,  7.51it/s]


Confusion matrix for epoch 63:
[[ 6 19]
 [ 5 81]]
Epoch 63/99, Val F1 Score: 0.7499, Val Recall: 0.7838
Epoch 63/99, Val Loss: 0.7256, Val Accuracy: 0.7838


Train Epoch 64: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 64/99, Train Loss: 0.1880, Train Accuracy: 0.8919


Val Epoch 64: 100%|██████████| 28/28 [00:03<00:00,  7.54it/s]


Confusion matrix for epoch 64:
[[ 5 20]
 [ 3 83]]
Epoch 64/99, Val F1 Score: 0.7487, Val Recall: 0.7928
Epoch 64/99, Val Loss: 0.7067, Val Accuracy: 0.7928


Train Epoch 65: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 65/99, Train Loss: 0.1839, Train Accuracy: 0.8839


Val Epoch 65: 100%|██████████| 28/28 [00:03<00:00,  7.44it/s]


Confusion matrix for epoch 65:
[[ 7 18]
 [ 6 80]]
Epoch 65/99, Val F1 Score: 0.7567, Val Recall: 0.7838
Epoch 65/99, Val Loss: 0.6940, Val Accuracy: 0.7838


Train Epoch 66: 100%|██████████| 250/250 [01:38<00:00,  2.55it/s]


Epoch 66/99, Train Loss: 0.1665, Train Accuracy: 0.8849


Val Epoch 66: 100%|██████████| 28/28 [00:03<00:00,  7.54it/s]


Confusion matrix for epoch 66:
[[ 7 18]
 [ 5 81]]
Epoch 66/99, Val F1 Score: 0.7637, Val Recall: 0.7928
Epoch 66/99, Val Loss: 0.7022, Val Accuracy: 0.7928


Train Epoch 67: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 67/99, Train Loss: 0.1530, Train Accuracy: 0.8969


Val Epoch 67: 100%|██████████| 28/28 [00:03<00:00,  7.41it/s]


Confusion matrix for epoch 67:
[[ 5 20]
 [ 4 82]]
Epoch 67/99, Val F1 Score: 0.7421, Val Recall: 0.7838
Epoch 67/99, Val Loss: 0.6800, Val Accuracy: 0.7838


Train Epoch 68: 100%|██████████| 250/250 [01:38<00:00,  2.53it/s]


Epoch 68/99, Train Loss: 0.1580, Train Accuracy: 0.8919


Val Epoch 68: 100%|██████████| 28/28 [00:03<00:00,  7.43it/s]


Confusion matrix for epoch 68:
[[ 7 18]
 [ 4 82]]
Epoch 68/99, Val F1 Score: 0.7707, Val Recall: 0.8018
Epoch 68/99, Val Loss: 0.6149, Val Accuracy: 0.8018


Train Epoch 69: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 69/99, Train Loss: 0.1622, Train Accuracy: 0.8989


Val Epoch 69: 100%|██████████| 28/28 [00:03<00:00,  7.36it/s]


Confusion matrix for epoch 69:
[[ 5 20]
 [ 5 81]]
Epoch 69/99, Val F1 Score: 0.7355, Val Recall: 0.7748
Epoch 69/99, Val Loss: 0.7777, Val Accuracy: 0.7748


Train Epoch 70: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 70/99, Train Loss: 0.1493, Train Accuracy: 0.8959


Val Epoch 70: 100%|██████████| 28/28 [00:03<00:00,  7.43it/s]


Confusion matrix for epoch 70:
[[ 8 17]
 [ 5 81]]
Epoch 70/99, Val F1 Score: 0.7770, Val Recall: 0.8018
Epoch 70/99, Val Loss: 0.6649, Val Accuracy: 0.8018


Train Epoch 71: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 71/99, Train Loss: 0.1464, Train Accuracy: 0.8929


Val Epoch 71: 100%|██████████| 28/28 [00:03<00:00,  7.58it/s]


Confusion matrix for epoch 71:
[[ 8 17]
 [ 5 81]]
Epoch 71/99, Val F1 Score: 0.7770, Val Recall: 0.8018
Epoch 71/99, Val Loss: 0.6592, Val Accuracy: 0.8018


Train Epoch 72: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 72/99, Train Loss: 0.1355, Train Accuracy: 0.8989


Val Epoch 72: 100%|██████████| 28/28 [00:03<00:00,  7.55it/s]


Confusion matrix for epoch 72:
[[10 15]
 [ 8 78]]
Epoch 72/99, Val F1 Score: 0.7800, Val Recall: 0.7928
Epoch 72/99, Val Loss: 0.6475, Val Accuracy: 0.7928


Train Epoch 73: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 73/99, Train Loss: 0.1439, Train Accuracy: 0.8949


Val Epoch 73: 100%|██████████| 28/28 [00:03<00:00,  7.47it/s]


Confusion matrix for epoch 73:
[[11 14]
 [ 4 82]]
Epoch 73/99, Val F1 Score: 0.8220, Val Recall: 0.8378
Epoch 73/99, Val Loss: 0.6626, Val Accuracy: 0.8378


Train Epoch 74: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 74/99, Train Loss: 0.1385, Train Accuracy: 0.9039


Val Epoch 74: 100%|██████████| 28/28 [00:03<00:00,  7.41it/s]


Confusion matrix for epoch 74:
[[ 8 17]
 [ 5 81]]
Epoch 74/99, Val F1 Score: 0.7770, Val Recall: 0.8018
Epoch 74/99, Val Loss: 0.6996, Val Accuracy: 0.8018


Train Epoch 75: 100%|██████████| 250/250 [01:38<00:00,  2.55it/s]


Epoch 75/99, Train Loss: 0.1435, Train Accuracy: 0.8969


Val Epoch 75: 100%|██████████| 28/28 [00:03<00:00,  7.51it/s]


Confusion matrix for epoch 75:
[[10 15]
 [ 5 81]]
Epoch 75/99, Val F1 Score: 0.8022, Val Recall: 0.8198
Epoch 75/99, Val Loss: 0.6490, Val Accuracy: 0.8198


Train Epoch 76: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 76/99, Train Loss: 0.1103, Train Accuracy: 0.9209


Val Epoch 76: 100%|██████████| 28/28 [00:03<00:00,  7.37it/s]


Confusion matrix for epoch 76:
[[ 6 19]
 [ 4 82]]
Epoch 76/99, Val F1 Score: 0.7567, Val Recall: 0.7928
Epoch 76/99, Val Loss: 0.7865, Val Accuracy: 0.7928


Train Epoch 77: 100%|██████████| 250/250 [01:38<00:00,  2.55it/s]


Epoch 77/99, Train Loss: 0.1429, Train Accuracy: 0.8979


Val Epoch 77: 100%|██████████| 28/28 [00:03<00:00,  7.40it/s]


Confusion matrix for epoch 77:
[[ 6 19]
 [ 4 82]]
Epoch 77/99, Val F1 Score: 0.7567, Val Recall: 0.7928
Epoch 77/99, Val Loss: 0.7190, Val Accuracy: 0.7928


Train Epoch 78: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 78/99, Train Loss: 0.1146, Train Accuracy: 0.9179


Val Epoch 78: 100%|██████████| 28/28 [00:03<00:00,  7.45it/s]


Confusion matrix for epoch 78:
[[ 6 19]
 [ 4 82]]
Epoch 78/99, Val F1 Score: 0.7567, Val Recall: 0.7928
Epoch 78/99, Val Loss: 0.7959, Val Accuracy: 0.7928


Train Epoch 79: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 79/99, Train Loss: 0.1340, Train Accuracy: 0.8969


Val Epoch 79: 100%|██████████| 28/28 [00:03<00:00,  7.40it/s]


Confusion matrix for epoch 79:
[[ 8 17]
 [ 4 82]]
Epoch 79/99, Val F1 Score: 0.7842, Val Recall: 0.8108
Epoch 79/99, Val Loss: 0.6963, Val Accuracy: 0.8108


Train Epoch 80: 100%|██████████| 250/250 [01:38<00:00,  2.55it/s]


Epoch 80/99, Train Loss: 0.1164, Train Accuracy: 0.9159


Val Epoch 80: 100%|██████████| 28/28 [00:03<00:00,  7.49it/s]


Confusion matrix for epoch 80:
[[ 6 19]
 [ 5 81]]
Epoch 80/99, Val F1 Score: 0.7499, Val Recall: 0.7838
Epoch 80/99, Val Loss: 0.8265, Val Accuracy: 0.7838


Train Epoch 81: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 81/99, Train Loss: 0.0983, Train Accuracy: 0.9319


Val Epoch 81: 100%|██████████| 28/28 [00:03<00:00,  7.39it/s]


Confusion matrix for epoch 81:
[[ 8 17]
 [ 5 81]]
Epoch 81/99, Val F1 Score: 0.7770, Val Recall: 0.8018
Epoch 81/99, Val Loss: 0.7767, Val Accuracy: 0.8018


Train Epoch 82: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 82/99, Train Loss: 0.1221, Train Accuracy: 0.9039


Val Epoch 82: 100%|██████████| 28/28 [00:03<00:00,  7.43it/s]


Confusion matrix for epoch 82:
[[ 9 16]
 [ 5 81]]
Epoch 82/99, Val F1 Score: 0.7898, Val Recall: 0.8108
Epoch 82/99, Val Loss: 0.7001, Val Accuracy: 0.8108


Train Epoch 83: 100%|██████████| 250/250 [01:37<00:00,  2.55it/s]


Epoch 83/99, Train Loss: 0.1123, Train Accuracy: 0.9139


Val Epoch 83: 100%|██████████| 28/28 [00:03<00:00,  7.48it/s]


Confusion matrix for epoch 83:
[[ 6 19]
 [ 4 82]]
Epoch 83/99, Val F1 Score: 0.7567, Val Recall: 0.7928
Epoch 83/99, Val Loss: 0.8710, Val Accuracy: 0.7928


Train Epoch 84: 100%|██████████| 250/250 [01:38<00:00,  2.53it/s]


Epoch 84/99, Train Loss: 0.1149, Train Accuracy: 0.9169


Val Epoch 84: 100%|██████████| 28/28 [00:03<00:00,  7.55it/s]


Confusion matrix for epoch 84:
[[ 7 18]
 [ 5 81]]
Epoch 84/99, Val F1 Score: 0.7637, Val Recall: 0.7928
Epoch 84/99, Val Loss: 0.7122, Val Accuracy: 0.7928


Train Epoch 85: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 85/99, Train Loss: 0.1159, Train Accuracy: 0.9149


Val Epoch 85: 100%|██████████| 28/28 [00:03<00:00,  7.67it/s]


Confusion matrix for epoch 85:
[[ 8 17]
 [ 5 81]]
Epoch 85/99, Val F1 Score: 0.7770, Val Recall: 0.8018
Epoch 85/99, Val Loss: 0.7098, Val Accuracy: 0.8018


Train Epoch 86: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 86/99, Train Loss: 0.1091, Train Accuracy: 0.9059


Val Epoch 86: 100%|██████████| 28/28 [00:03<00:00,  7.44it/s]


Confusion matrix for epoch 86:
[[ 6 19]
 [ 4 82]]
Epoch 86/99, Val F1 Score: 0.7567, Val Recall: 0.7928
Epoch 86/99, Val Loss: 0.8238, Val Accuracy: 0.7928


Train Epoch 87: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 87/99, Train Loss: 0.1195, Train Accuracy: 0.9029


Val Epoch 87: 100%|██████████| 28/28 [00:03<00:00,  7.41it/s]


Confusion matrix for epoch 87:
[[ 7 18]
 [ 4 82]]
Epoch 87/99, Val F1 Score: 0.7707, Val Recall: 0.8018
Epoch 87/99, Val Loss: 0.7977, Val Accuracy: 0.8018


Train Epoch 88: 100%|██████████| 250/250 [01:37<00:00,  2.55it/s]


Epoch 88/99, Train Loss: 0.1082, Train Accuracy: 0.9109


Val Epoch 88: 100%|██████████| 28/28 [00:03<00:00,  7.47it/s]


Confusion matrix for epoch 88:
[[ 8 17]
 [ 5 81]]
Epoch 88/99, Val F1 Score: 0.7770, Val Recall: 0.8018
Epoch 88/99, Val Loss: 0.7652, Val Accuracy: 0.8018


Train Epoch 89: 100%|██████████| 250/250 [01:37<00:00,  2.55it/s]


Epoch 89/99, Train Loss: 0.1025, Train Accuracy: 0.9069


Val Epoch 89: 100%|██████████| 28/28 [00:03<00:00,  7.51it/s]


Confusion matrix for epoch 89:
[[ 7 18]
 [ 4 82]]
Epoch 89/99, Val F1 Score: 0.7707, Val Recall: 0.8018
Epoch 89/99, Val Loss: 0.8082, Val Accuracy: 0.8018


Train Epoch 90: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 90/99, Train Loss: 0.1081, Train Accuracy: 0.9119


Val Epoch 90: 100%|██████████| 28/28 [00:03<00:00,  7.51it/s]


Confusion matrix for epoch 90:
[[ 9 16]
 [ 6 80]]
Epoch 90/99, Val F1 Score: 0.7825, Val Recall: 0.8018
Epoch 90/99, Val Loss: 0.7620, Val Accuracy: 0.8018


Train Epoch 91: 100%|██████████| 250/250 [01:38<00:00,  2.55it/s]


Epoch 91/99, Train Loss: 0.1236, Train Accuracy: 0.9019


Val Epoch 91: 100%|██████████| 28/28 [00:03<00:00,  7.46it/s]


Confusion matrix for epoch 91:
[[12 13]
 [ 7 79]]
Epoch 91/99, Val F1 Score: 0.8106, Val Recall: 0.8198
Epoch 91/99, Val Loss: 0.6959, Val Accuracy: 0.8198


Train Epoch 92: 100%|██████████| 250/250 [01:37<00:00,  2.55it/s]


Epoch 92/99, Train Loss: 0.1165, Train Accuracy: 0.9009


Val Epoch 92: 100%|██████████| 28/28 [00:03<00:00,  7.44it/s]


Confusion matrix for epoch 92:
[[ 7 18]
 [ 5 81]]
Epoch 92/99, Val F1 Score: 0.7637, Val Recall: 0.7928
Epoch 92/99, Val Loss: 0.8191, Val Accuracy: 0.7928


Train Epoch 93: 100%|██████████| 250/250 [01:37<00:00,  2.57it/s]


Epoch 93/99, Train Loss: 0.1016, Train Accuracy: 0.9129


Val Epoch 93: 100%|██████████| 28/28 [00:03<00:00,  7.48it/s]


Confusion matrix for epoch 93:
[[ 7 18]
 [ 4 82]]
Epoch 93/99, Val F1 Score: 0.7707, Val Recall: 0.8018
Epoch 93/99, Val Loss: 0.7983, Val Accuracy: 0.8018


Train Epoch 94: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 94/99, Train Loss: 0.1002, Train Accuracy: 0.9229


Val Epoch 94: 100%|██████████| 28/28 [00:03<00:00,  7.41it/s]


Confusion matrix for epoch 94:
[[ 8 17]
 [ 4 82]]
Epoch 94/99, Val F1 Score: 0.7842, Val Recall: 0.8108
Epoch 94/99, Val Loss: 0.8094, Val Accuracy: 0.8108


Train Epoch 95: 100%|██████████| 250/250 [01:38<00:00,  2.54it/s]


Epoch 95/99, Train Loss: 0.0982, Train Accuracy: 0.9229


Val Epoch 95: 100%|██████████| 28/28 [00:03<00:00,  7.43it/s]


Confusion matrix for epoch 95:
[[ 8 17]
 [ 5 81]]
Epoch 95/99, Val F1 Score: 0.7770, Val Recall: 0.8018
Epoch 95/99, Val Loss: 0.7883, Val Accuracy: 0.8018


Train Epoch 96: 100%|██████████| 250/250 [01:37<00:00,  2.56it/s]


Epoch 96/99, Train Loss: 0.1240, Train Accuracy: 0.8959


Val Epoch 96: 100%|██████████| 28/28 [00:03<00:00,  7.47it/s]


Confusion matrix for epoch 96:
[[ 9 16]
 [ 5 81]]
Epoch 96/99, Val F1 Score: 0.7898, Val Recall: 0.8108
Epoch 96/99, Val Loss: 0.7255, Val Accuracy: 0.8108


Train Epoch 97: 100%|██████████| 250/250 [01:38<00:00,  2.55it/s]


Epoch 97/99, Train Loss: 0.1147, Train Accuracy: 0.9059


Val Epoch 97: 100%|██████████| 28/28 [00:03<00:00,  7.43it/s]


Confusion matrix for epoch 97:
[[ 8 17]
 [ 5 81]]
Epoch 97/99, Val F1 Score: 0.7770, Val Recall: 0.8018
Epoch 97/99, Val Loss: 0.7756, Val Accuracy: 0.8018


Train Epoch 98: 100%|██████████| 250/250 [01:37<00:00,  2.55it/s]


Epoch 98/99, Train Loss: 0.1093, Train Accuracy: 0.9209


Val Epoch 98: 100%|██████████| 28/28 [00:03<00:00,  7.49it/s]


Confusion matrix for epoch 98:
[[ 7 18]
 [ 4 82]]
Epoch 98/99, Val F1 Score: 0.7707, Val Recall: 0.8018
Epoch 98/99, Val Loss: 0.8064, Val Accuracy: 0.8018


Train Epoch 99: 100%|██████████| 250/250 [01:38<00:00,  2.55it/s]


Epoch 99/99, Train Loss: 0.0926, Train Accuracy: 0.9219


Val Epoch 99: 100%|██████████| 28/28 [00:03<00:00,  7.54it/s]


Confusion matrix for epoch 99:
[[ 9 16]
 [ 6 80]]
Epoch 99/99, Val F1 Score: 0.7825, Val Recall: 0.8018
Epoch 99/99, Val Loss: 0.7417, Val Accuracy: 0.8018
Training complete. Best validation accuracy: 0.8378 at epoch 22
